Adds a basic JsonStreamQueryTransformer
comunica/json-event-parser.js pull request #1
Opened 2022-09-06 16:55 UTC by Tpt

2022-09-08 12:53 UTC, rubensworks requested changes

2022-09-08 12:53 UTC, rubensworks commented on package.json
> +        "branches": 95,
Can we make this all 100? :)

2022-09-10 07:47 UTC, Tpt commented on package.json
> +        "branches": 95,
Yes, would be great! jsonparse code coverage was not great I already improved it a bit with `[JSONTestSuite](https://github.com/nst/JSONTestSuite/tree/d64aefb55228d9584d3e5b2433f720ea8fd00c82)` but there is indeed still work to do. But it's unrelated to this PR imho (the introduced code as a 100% code coverage).

2022-09-10 07:50 UTC, Tpt commented on lib/JsonStreamQueryTransformer.ts
> +export class JsonStreamQueryTransformer extends Transform {
Done with `JsonStreamPathTransformer`. What is implemented is a subset of JSONPath so it should be possible to add JSONPath without breaking the API.

2022-09-15 11:40 UTC, rubensworks approved these changes
Looks good to me!

2022-09-16 12:58 UTC, merged