100% code coverage
comunica/json-event-parser.js pull request #6
Opened 2022-10-13 06:28 UTC by Tpt

2022-10-14 08:35 UTC, Tpt commented
@rubensworks Could you add this repository to Coveralls?

2022-10-15 13:35 UTC, rubensworks commented
AFAIK, this isn't needed (anymore).

From the action's readme:

> You don't need to add the repo to Coveralls first, it will be created when receiving the post.

I think [this part](https://github.com/comunica/comunica/blob/master/.github/workflows/ci.yml#L39-L44) of the CI file is missing.

2022-10-17 06:57 UTC, Tpt commented
@rubensworks Thank you. It's now fixed.

2022-10-31 07:33 UTC, rubensworks requested changes

2022-10-31 07:33 UTC, rubensworks commented on lib/JsonEventParser.ts
> +    throw new Error(`Not supported token code ${code}`);
Not a big fan of skipping coverage lines 😅 
Could we add a small test for this case?

2022-10-31 07:33 UTC, rubensworks commented on lib/JsonEventParser.ts
> +    /* istanbul ignore next */
Also here?

2022-10-31 08:27 UTC, Tpt commented on lib/JsonEventParser.ts
> +    throw new Error(`Not supported token code ${code}`);
This line is here to make the TS compiler happy by returning a string always but can't be evaluated anywhere (the method is private and called only with valid error codes). To cover it I would have to make it public or hack around the TypeScript compiler. I have not found a proper way to state that a piece of code is unreachable in TS or state in the tpye system that only keys of a given object are allowed.

2022-10-31 09:15 UTC, rubensworks commented on lib/JsonEventParser.ts
> +    throw new Error(`Not supported token code ${code}`);
> To cover it I would have to make it public or hack around the TypeScript compiler. I have not found a proper way to state that a piece of code is unreachable in TS or state in the tpye system that only keys of a given object are allowed.

I guess casting the parser to `any` and invoking the private method could work. (or might have to become `protected`).

2022-10-31 09:16 UTC, rubensworks commented on lib/JsonEventParser.ts
> +    /* istanbul ignore next */
I would definitely keep it indeed. Should be possible to unit test it by casting the parser to `any` like above.

2022-10-31 14:26 UTC, Tpt commented on lib/JsonEventParser.ts
> +    /* istanbul ignore next */
Done. Thanks!

2022-10-31 14:44 UTC, merged

2022-10-31 14:47 UTC, rubensworks commented
Super! Released as `1.0.0-beta.3`.